### ISSUE TITLE
Possible missing gem

### ISSUE THREAD

**Issue by ToJen** [hswick/w3#16]
Is there a missing gem dependency? After running `bundle && rails server`:

```ruby
/home/user/.rvm/gems/ruby-2.4.0/bundler/gems/w3-945bfbe9334f/lib/w3.rb:6:in `require': cannot load such file -- digest/sha3 (LoadError)
```

**Comment by hswick** [comment]
Yes, I haven't added digest-sha3 to gemspec because it will throw an error on ubuntu. For now I've been using this `gem "digest-sha3", :git => 'https://github.com/Eugenpaul/digest-sha3-ruby.git', :branch => 'fix_format_security'` in my Gemfile. 

I'm not entirely sure what the path forward is on this

**Comment by ToJen** [comment]
If I manually add `digest-sha3` to my Gemfile would it work?

**Comment by hswick** [comment]
I think so :cold_sweat:

**Comment by ToJen** [comment]
Did that and got this:

```bash
user:path/to/project$ rails server
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying toload the gem 'w3'. (Bundler::GemRequireError)
Gem Load Error is: wrong number of arguments (given 1, expected 2)
Backtrace for gem load error is:
/home/user/.rvm/gems/ruby-2.4.0/gems/speculation-0.4.2/lib/speculation.rb:618:in `valid?'
/home/user/.rvm/gems/ruby-2.4.0/bundler/gems/w3-945bfbe9334f/lib/w3/eth_type.rb:41:in `<module:ETH_Type>'
/home/user/.rvm/gems/ruby-2.4.0/bundler/gems/w3-945bfbe9334f/lib/w3/eth_type.rb:2:in `<module:W3>'
/home/user/.rvm/gems/ruby-2.4.0/bundler/gems/w3-945bfbe9334f/lib/w3/eth_type.rb:1:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.0/bundler/gems/w3-945bfbe9334f/lib/w3.rb:18:in `require'
/home/user/.rvm/gems/ruby-2.4.0/bundler/gems/w3-945bfbe9334f/lib/w3.rb:18:in `<module:W3>'
/home/user/.rvm/gems/ruby-2.4.0/bundler/gems/w3-945bfbe9334f/lib/w3.rb:17:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/home/user/path/to/project/config/application.rb:7:in `<top (required)>'
```

**Comment by hswick** [comment]
Hmmm, I'm starting to think that moving the digest-sha3 code to this repo is the only long term solution

**Comment by ToJen** [comment]
I agree. The other web3 Ruby libraries don't work well with HttpProviders compared to `web3.js` but this project looks more promising. I don't see the point of restricting to local IPC connections or Parity nodes.
